---
- name: Create SSL directory on Nextcloud server
  ansible.builtin.file:
    path: "{{ mariadb_ssl_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0750"

- name: Copy SSL certs to Nextcloud server
  ansible.builtin.copy:
    src: "/tmp/{{ item.file }}"
    dest: "{{ mariadb_ssl_dir }}/{{ item.file }}"
    owner: www-data
    group: www-data
    mode: "{{ item.mode }}"
  loop:
    - { file: "ca.crt",      mode: "0640" }
    - { file: "mariadb.crt", mode: "0640" }
    - { file: "mariadb.key", mode: "0600" }